/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shirt_baked.glb
*/

"use client"

import React from 'react'
import {useGLTF} from '@react-three/drei'


export function Tshirt({transitionColor}, props: JSX.IntrinsicElements["group"]) {
    const {nodes, materials} = useGLTF('/models/shirt_baked.glb')


    return (
        <>

            <group {...props} dispose={null}>
                <mesh geometry={nodes.T_Shirt_male.geometry} material={materials.lambert1}
                      material-color={transitionColor} scale={3}></mesh>
            </group>
        </>
    )
}

useGLTF.preload('/models/shirt_baked.glb')
